import PDFDocument from 'pdfkit'
import { QUESTIONNAIRE_SECTIONS } from '@/lib/questionnaireData'
import { AnswerValue, Question } from '@/types'

const GOLD = '#E07820'
const NAVY = '#111111'
const GRAY = '#6b7280'
const LIGHT_GRAY = '#d1d5db'

function hasAnswer(val: AnswerValue | undefined): boolean {
  if (!val) return false
  if (Array.isArray(val)) return val.length > 0
  return String(val).trim().length > 0
}

function formatAnswer(val: AnswerValue | undefined, question: Question): string {
  if (!hasAnswer(val)) return 'Not answered'
  if (Array.isArray(val)) return val.join(', ')
  const s = String(val).trim()
  if (s === 'yes') return 'Yes'
  if (s === 'no') return 'No'
  if (s === 'not_sure') return 'Not Sure'
  if (question.type === 'currency') return `$${s}`
  return s
}

export function generateAnswersPdf(
  clientName: string,
  caseType: string,
  phone: string,
  answers: Record<string, AnswerValue>
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'LETTER', bufferPages: true })
    const chunks: Buffer[] = []
    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const bottom = () => doc.page.height - doc.page.margins.bottom
    const ensureSpace = (needed: number) => {
      if (doc.y + needed > bottom()) doc.addPage()
    }

    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(16)
      .text('Law Offices of Jack D. Josephson, APC', { align: 'center' })
    doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(9)
      .text('CLIENT INTAKE QUESTIONNAIRE', { align: 'center', characterSpacing: 1 })
    doc.moveDown(1.2)

    doc.fillColor('#000000').font('Helvetica-Bold').fontSize(13).text(clientName)
    doc.fillColor(GRAY).font('Helvetica').fontSize(10)
      .text(`Case Type: ${caseType}`)
      .text(`Phone: ${phone}`)
      .text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`)
    doc.moveDown(0.8)

    doc.strokeColor(LIGHT_GRAY).lineWidth(1)
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .stroke()
    doc.moveDown(1)

    let anySections = false

    for (const section of QUESTIONNAIRE_SECTIONS) {
      const answered = section.questions.filter(q => hasAnswer(answers[q.id]))
      if (answered.length === 0) continue
      anySections = true

      ensureSpace(40)
      doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(11)
        .text(section.title.toUpperCase(), { characterSpacing: 0.5 })
      doc.moveDown(0.4)

      for (const q of answered) {
        ensureSpace(30)
        doc.fillColor(GRAY).font('Helvetica-Bold').fontSize(9).text(q.label)
        doc.fillColor('#000000').font('Helvetica').fontSize(10.5).text(formatAnswer(answers[q.id], q))
        doc.moveDown(0.5)
      }
      doc.moveDown(0.5)
    }

    if (!anySections) {
      doc.fillColor(GRAY).font('Helvetica').fontSize(11).text('No answers submitted yet.')
    }

    const pageCount = doc.bufferedPageRange().count
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i)
      // Writing past the bottom margin trips pdfkit's auto-pagination and
      // silently appends a blank page, so the margin is dropped to 0 only
      // for this one write.
      const originalBottomMargin = doc.page.margins.bottom
      doc.page.margins.bottom = 0
      doc.fillColor(GRAY).font('Helvetica').fontSize(8)
        .text(
          'Attorney-Client Privileged & Confidential · Generated by JACKLAW Client Portal',
          doc.page.margins.left,
          doc.page.height - originalBottomMargin + 18,
          { align: 'center', width: doc.page.width - doc.page.margins.left - doc.page.margins.right }
        )
      doc.page.margins.bottom = originalBottomMargin
    }

    doc.end()
  })
}
