import { QuestionnaireSection } from '@/types'

/**
 * Module 2 in Chinese.
 *
 * Only what the client reads: section titles, question labels, help text,
 * placeholders and the words shown for each answer choice. Ids, types, option
 * VALUES, exclusivity, repeat rules and skip logic all come from
 * lib/module2Data.ts and are merged over this file at read time, the same way
 * Module 1 does it — which is what lets a Spanish reader's choice be filed in
 * English and a gate mean one thing in four languages.
 */
export const MODULE_2_SECTIONS_ZH: QuestionnaireSection[] = [
  {
    id: "m2_meal_breaks",
    title: "用餐休息（吃饭时间）",
    questions: [
      { id: "m2_meal_given", label: "在您工作超过五小时的日子里，您有没有拿到用餐休息时间？", type: "select", options: ["每天都有", "有些日子有", "没有", "我的工作日没有超过五小时", "不确定"] },
      { id: "m2_meal_start_time", label: "您第一次用餐休息通常大概几点开始？", type: "text", helpText: "写一个时间，或写\"时间不固定\"，或写\"我没有吃饭时间\"。写\"不确定\"也可以。", placeholder: "大约下午12:30" },
      { id: "m2_meal_minutes_free", label: "过了多少分钟之后，您就又得开始做事了？", type: "select", options: ["30分钟或以上", "20-29分钟", "10-19分钟", "不到10分钟", "没有用餐休息", "不固定", "不确定"] },
      { id: "m2_meal_where", label: "您通常在哪里吃饭？", type: "text", placeholder: "例如：员工餐厅、办公桌、收银台、车里，或者户外" },
      { id: "m2_meal_what_happened", label: "在吃饭期间，下面哪些情况发生过？", type: "multiselect", options: ["我没有做任何工作，也不用随时待命", "我自己选择干活，但没有人要求或期望我这样做", "老板或同事来问我问题", "我接待了顾客、病人、住户或其他人", "我接了工作电话、对讲机、短信、警报，或去开门", "我看着柜台、机器、工作区域或看着人", "我签收了送货，或做了一件小事", "我必须随时待命，以防有活儿要做", "我一边吃一边继续工作", "老板叫我等一等、不要吃饭，或先把活干完", "工作太忙，或没有人能替我", "还发生了其他情况", "不确定"], helpText: "凡是发生过的都请选上。" },
      { id: "m2_meal_could_leave", label: "吃饭期间，如果您想离开工作场所，可以离开吗？", type: "select", options: ["可以", "不可以", "要经过批准才可以", "不确定"] },
      { id: "m2_meal_redone", label: "如果工作打断了您的吃饭时间，后来公司有没有重新给您完整的30分钟用餐休息？", type: "select", options: ["每次都有", "有时候有", "从来没有", "不确定", "没有发生过这种情况"] },
      { id: "m2_meal_days_per_week", label: "在一个普通的星期里，有多少个工作日出现过这些情况：没吃上饭、开始得太晚、不到30分钟、吃饭时还在干活，或者必须随时待命？", type: "select", options: ["0", "1", "2", "3", "4", "5", "6", "7", "不固定", "不确定"] },
      { id: "m2_meal_problem_start", label: "用餐休息的问题大概是什么时候开始的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，或者当时工作上发生的某件事——比如\"新经理来的那一周\"也是有效的回答。写\"不确定\"也可以。" },
      { id: "m2_meal_problem_end", label: "如果这个用餐休息的问题已经停止了，大概是什么时候停止的？", type: "text", helpText: "可以写确切日期、您的大致估计、\"现在还在发生\"，或者当时工作上发生的某件事。写\"不确定\"也可以。" },
      { id: "m2_second_meal_given", label: "在您工作超过10小时的日子里，您有没有拿到第二次30分钟的用餐休息？", type: "select", options: ["每天都有", "有些日子有", "没有", "我没有工作超过10小时", "不确定"], helpText: "如果您的工作日从来没有超过10小时，请说明——最后一个选项就是给这种情况用的。" },
      { id: "m2_second_meal_time", label: "第二次用餐休息通常大概几点开始？", type: "text", helpText: "写一个时间，或写\"时间不固定\"。写\"不确定\"也可以。" },
      { id: "m2_meal_waiver", label: "您有没有签过文件，同意放弃吃饭时间或在吃饭时间工作？", type: "select", options: ["没有", "有，同意放弃吃饭时间", "有，同意一边吃一边工作", "我签过东西，但不知道上面写的是什么", "不确定"] },
    ],
  },
  {
    id: "m2_rest_breaks",
    title: "带薪休息时间（工间休息）",
    questions: [
      { id: "m2_rest_count", label: "在正常的一个工作日里，您能得到几次带薪的10分钟休息？", type: "select", options: ["0次", "1次", "2次", "3次或以上", "不固定", "不确定"], helpText: "第1部分里已填写您平时每天工作多少小时——请按那样长度的一天来回答。" },
      { id: "m2_rest_full_ten", label: "每次休息都有满满10分钟吗？", type: "select", options: ["每次都有", "有些有", "没有", "不确定"] },
      { id: "m2_rest_what_happened", label: "在休息时间里，出现过下面哪些情况？", type: "multiselect", options: ["我没有干活，这段时间是自己的", "我必须打卡下班（下钟）", "我回答了问题，或帮了主管、同事、客户或供应商", "我接了工作电话、对讲机、短信、警报，或去开门", "我要看着柜台、机器、某个区域或看着人", "我必须随时待命，以防有活要干", "我必须先请示才能去休息", "别人让我等一等，或者不准我休息", "活太忙，或者没人能顶替我", "休息时间被并到午饭里，或被放在上班前或下班前", "上厕所被算成了我的休息时间", "还有其他情况", "不确定"], helpText: "发生过的都请选上。" },
      { id: "m2_rest_phone", label: "休息时间里，您可以用自己的手机吗？", type: "select", options: ["可以", "不可以", "有时可以", "不确定"] },
      { id: "m2_rest_leave_site", label: "休息时间里，您可以离开工作场所吗？", type: "select", options: ["可以", "不可以", "有时可以", "不确定"] },
      { id: "m2_rest_eat_drink", label: "休息时间里，您可以吃东西或喝水吗？", type: "select", options: ["可以", "不可以", "有时可以", "不确定"] },
      { id: "m2_rest_days_per_week", label: "在正常的一周里，有多少个工作日您没能休息，或者休息时间被占用了一部分？", type: "select", options: ["0天", "1天", "2天", "3天", "4天", "5天", "6天", "7天", "不固定", "不确定"] },
      { id: "m2_rest_problem_start", label: "休息时间的问题大概是从什么时候开始的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，也可以写工作中发生的某件事——比如“新经理上任的那一周”就是很好的回答。写“不确定”也可以。" },
      { id: "m2_rest_problem_end", label: "休息时间的问题大概是什么时候结束的？（如果已经结束）", type: "text", helpText: "可以写确切日期、您的大致估计、“现在还在发生”，或者工作中发生的某件事。写“不确定”也可以。" },
    ],
  },
  {
    id: "m2_find_off_clock",
    title: "您没有得到报酬的工作",
    questions: [
      { id: "m2_worked_off_clock", label: "您有没有在没有打卡上班的时候做过工作？", type: "select", options: ["没有", "有", "可能有", "不确定"], helpText: "不管您怎么回答，后面的问题还是会问到一些具体的事情。其中有些事情当时您可能并不觉得算是工作。" },
      { id: "m2_before_clock_in", label: "在您打卡上班之前，您有没有做过下面这些事？", type: "multiselect", options: ["开门或开大门", "关掉警报器或打开灯", "去拿钥匙、工具、食物、文件或用品", "开启电脑、收银机、机器或工作车辆", "穿上规定的工作服或安全装备", "布置、上货、打扫或准备东西", "查看工作记录、留言或任务安排", "参加会议或谈论这一班的工作", "帮助顾客或其他员工", "等老板、等钥匙、等设备或等到打卡时间", "其他事情", "以上都没有", "不确定"], helpText: "请把您做过的都选上。" },
      { id: "m2_after_clock_out", label: "在您打卡下班之后，您有没有做过下面这些事？", type: "multiselect", options: ["打扫或上货", "关门或锁门、锁大门", "关灯或设置警报器", "关掉电脑、收银机、机器或车辆", "清点现金、小费或货品", "写完记录、报告或其他文件", "向下一班的人交接情况", "帮助顾客、老板或其他员工", "等待检查随身包或过安检", "等别人放您走", "其他事情", "以上都没有", "不确定"], helpText: "请把您做过的都选上。" },
      { id: "m2_away_from_job", label: "不在工作场所的时候，您有没有做过下面这些事，而且没有把这些时间算进工时记录里？", type: "multiselect", options: ["接听工作电话", "看或回复工作短信", "看或回复电子邮件、手机应用上的消息", "查看排班、路线或任务", "填写表格或报告", "发送照片或工作信息", "帮助顾客或其他员工", "参加网上培训", "用自己的手机或电脑处理工作", "其他事情", "以上都没有", "不确定"], helpText: "请把您做过的都选上。" },
      { id: "m2_unclocked_meetings", label: "在没有打卡上班的情况下，您有没有参加过下面这些？", type: "multiselect", options: ["员工会议", "班前班后会", "安全讲话", "培训", "入职介绍", "考核或书面警告的谈话", "与上一班或下一班的交接谈话", "其他", "以上都没有", "不确定"], helpText: "请把您参加过的都选上。" },
      { id: "m2_wait_and_travel", label: "到达公司要求您报到的地点之后，您在能打卡上班之前，是否还要等待、步行、乘车或开车？", type: "multiselect", options: ["在大门口或安检处等候", "等老板或带班的人", "等钥匙、工具、车辆或设备", "乘坐公司规定的班车或面包车", "从公司的一个区域开车或走到另一个区域", "等顾客、等装货、等路线或等派活", "其他情况", "没有", "不确定"], helpText: "从家里到公司要求您报到的第一个地点的正常路程不算在内。" },
      { id: "m2_most_frequent_pattern", label: "哪一类没有报酬的工作发生得最多？", type: "select", helpText: "下面是您刚才选的项目。请选出发生次数最多的那一项。" },
      { id: "m2_another_pattern", label: "还有别的没有报酬的工作也经常发生吗？", type: "select", options: ["有", "没有", "不确定"] },
      { id: "m2_other_frequent_patterns", label: "还有哪些没有报酬的工作也经常发生？", type: "multiselect", helpText: "请把经常发生的其他项目都选上。" },
    ],
  },
  {
    id: "m2_pattern",
    title: "关于这段没有拿到工资的工作",
    repeatFor: { fromQuestionIds: ["m2_most_frequent_pattern", "m2_other_frequent_patterns"], titleTemplate: "未付酬的工作 —— {instance}" },
    questions: [
      { id: "m2_p_what", label: "发生这种没有算工资的工作时，您具体做了些什么？", type: "textarea" },
      { id: "m2_p_who_asked", label: "是谁让您做这些工作，或者是谁定的这个规矩？", type: "select", options: ["老板（企业主）", "上司或经理", "带班的工人", "顾客或客户", "公司规定或系统要求", "没有人直接要求", "其他人", "不确定"] },
      { id: "m2_p_why_did_it", label: "如果没有人直接要求您，那您为什么还要做这些工作？", type: "multiselect", options: ["不做的话，工作没法开始", "不做的话，工作没法收尾", "这些活儿必须做完", "有顾客在等", "下一班的人需要", "没有别人可以做", "我担心不做会惹上麻烦", "大家都是这么做的", "我想帮忙，但没人要求我这样做", "这是我自己的选择", "其他原因", "不确定"] },
      { id: "m2_p_if_not_done", label: "如果您不做，最有可能发生什么？", type: "select", options: ["什么事都不会发生", "工作准备不好", "活儿会做不完", "顾客会投诉", "上司会不高兴", "我可能会被书面警告", "我的工时或班次可能会被减少", "下一班的人会有麻烦", "其他情况", "不确定"] },
      { id: "m2_p_could_wait", label: "您能不能等打卡上班以后、或者在打卡下班之前再做这些事？", type: "select", options: ["能", "不能", "有时可以", "不确定"] },
      { id: "m2_p_free_during_wait", label: "如果这里面包括等待或路上的时间，您能离开或自由支配这段时间吗？", type: "select", options: ["能", "不能", "只有一部分可以", "不确定"] },
      { id: "m2_p_who_knew", label: "有谁知道您在做这些工作？", type: "multiselect", options: ["老板（企业主）", "经理", "带班的工人", "做工资或办公室的人", "同事", "顾客或客户", "据我所知没有人知道", "其他人", "不确定"] },
      { id: "m2_p_how_they_knew", label: "那个人是怎么知道的？", type: "multiselect", options: ["看见我在做", "是他叫我做的", "是我告诉他的", "收到我的电话、短信、邮件或报告", "我做完以后，他用了这些成果", "知道开店或关店的活儿总得有人做", "看到摄像头、电脑、门禁、GPS、销售或警报记录", "多次看到这种情况", "其他情况", "不确定"] },
      { id: "m2_p_records", label: "哪些记录可能能证明这些工作？", type: "multiselect", options: ["考勤打卡记录", "排班表", "短信或群聊", "通话记录或语音留言", "电子邮件", "工作用的手机应用", "电脑登录记录", "收银机或销售记录", "警报、门禁、工牌或大门记录", "监控录像", "GPS 或车辆记录", "顾客、送货或工单记录", "照片或视频", "个人笔记或日历", "工资单或银行记录", "其他记录", "据我所知没有", "不确定"] },
      { id: "m2_p_could_clock_in_first", label: "您能在开始做这些工作之前先打卡上班吗？", type: "select", options: ["一直都可以", "有时可以", "不能", "不确定", "这一项不适用"] },
      { id: "m2_p_why_not_clock_in", label: "您为什么没有先打卡？", type: "multiselect", options: ["系统不让提前打卡", "打卡机离第一项工作的地方不近", "做完那件事之前我够不着打卡的地方", "需要上司批准", "不允许提前打卡", "有人叫我等到上班时间再打", "加时或加班需要批准", "打卡机或应用坏了", "我忘了", "我自己选择不打", "其他原因", "不确定"] },
      { id: "m2_p_could_stay_clocked_in", label: "您能一直不打下班卡，直到所有活儿都做完吗？", type: "select", options: ["一直都可以", "有时可以", "不能", "不确定", "这一项不适用"] },
      { id: "m2_p_why_clocked_out_early", label: "为什么活儿还没做完，您就打卡下班了？", type: "multiselect", options: ["上司让我打卡下班", "系统自动帮我打了下班卡", "我必须在规定的下班时间打卡", "不允许加时或加班", "我感到有压力，只能打卡下班", "必须先把收银机、小费或工作系统结清", "打卡机离最后一项工作的地方很远", "我忘了", "是我自己选择这么做的", "其他原因", "不确定"] },
      { id: "m2_p_rule_against", label: "公司有没有说过，员工不可以在没有打卡的情况下干活？", type: "select", options: ["有", "没有", "不确定"] },
      { id: "m2_p_boss_allowed_anyway", label: "即使有这条规定，上司是否仍然看到、要求、默许或使用了这些工作成果？", type: "select", options: ["是", "否", "可能", "不确定"] },
      { id: "m2_p_told_anyone", label: "您有没有向任何人反映过这段时间没算工资，或者要求过支付工资？", type: "select", options: ["有", "没有", "不确定"] },
      { id: "m2_p_told_who", label: "您跟谁说的？", type: "text", helpText: "可以写全名、名字、职位、外号，或者清楚的描述。" },
      { id: "m2_p_told_when", label: "您大概是什么时候告诉那个人的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，或者工作中发生的某件事——比如“新经理来的那一周”也是有效的回答。写“不确定”也没关系。" },
      { id: "m2_p_told_how", label: "您是通过什么方式告诉那个人的？", type: "select", options: ["当面说", "打电话", "短信", "电子邮件", "群聊", "书面投诉", "向政府部门提出申诉", "其他", "不确定"] },
      { id: "m2_p_told_what_said", label: "您当时说了什么？", type: "textarea", helpText: "用您自己的话写，尽量接近您记得的原话。" },
      { id: "m2_p_told_result", label: "您告诉那个人之后，发生了什么？", type: "textarea" },
      { id: "m2_p_started", label: "这种没有算工资的工作大概是从什么时候开始的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，或者工作中发生的某件事——比如“新经理来的那一周”也是有效的回答。写“不确定”也没关系。" },
      { id: "m2_p_stopped", label: "如果已经不再发生了，大概是什么时候停止的？", type: "text", helpText: "可以写确切日期、您的大致估计、“还在发生”，或者工作中发生的某件事。写“不确定”也没关系。" },
      { id: "m2_p_days_per_week", label: "在平常的一周里，这种情况有几天会发生？", type: "textarea", helpText: "写您的大致估计；如果可以，再写出您觉得合理的最少和最多天数。“情况有变化”和“不确定”都是有效的回答。", placeholder: "大致估计：4 天\n最少：3\n最多：5" },
      { id: "m2_p_minutes_per_day", label: "在发生这种情况的一天里，大概有多少分钟没有算工资？", type: "textarea", helpText: "写您的大致估计；如果可以，再写出您觉得合理的最少和最多数字。“情况有变化”和“不确定”都是有效的回答。", placeholder: "大致估计：20 分钟\n最少：15\n最多：30" },
      { id: "m2_p_how_sure", label: "对于没算工资的分钟数，您有多大把握？", type: "select", options: ["准确", "接近的估计", "范围比较大", "不确定"] },
      { id: "m2_p_pattern_changed", label: "这种情况有没有因为换了上司、换了工作、换了工作地点、改了排班、改了规定、放假或其他事情而发生变化？", type: "select", options: ["有", "没有", "不确定"] },
      { id: "m2_p_what_changed", label: "发生了什么变化？大概是什么时候变的？", type: "textarea", helpText: "每一项大的变化写一行，并写上大概发生的时间。" },
    ],
  },
  {
    id: "m2_overtime",
    title: "加班",
    questions: [
      { id: "m2_over_8_hours", label: "把您做过的所有工作都算上（包括没有打卡的时间），您平均多久会出现一天工作超过八小时的情况？", type: "select", options: ["从来没有", "正常一周里有1-2天", "3-4天", "5天或以上", "情况不固定", "不确定"] },
      { id: "m2_over_12_hours", label: "您多久会出现一天工作超过12小时的情况？", type: "select", options: ["从来没有", "不到一个月一次", "一个月几次", "一周几次", "情况不固定", "不确定"] },
      { id: "m2_over_40_hours", label: "您多久会出现一周工作超过40小时的情况？", type: "select", options: ["从来没有", "不到一个月一次", "正常一个月里有1-2周", "3-4周", "情况不固定", "不确定"] },
      { id: "m2_seven_days_running", label: "您有没有连续工作过七天？", type: "select", options: ["没有", "有，一两次", "有，很多次", "不确定"] },
      { id: "m2_all_hours_on_stub", label: "您实际工作的所有小时数，都有显示在您的工资单或工资记录上吗？", type: "select", options: ["每次都有", "有时候有", "没有", "我没有拿到工资单", "不确定"] },
      { id: "m2_overtime_on_stub", label: "对于一天超过八小时或一周超过40小时的部分，工资单上有没有把每一个多做的小时都按加班费算？", type: "select", options: ["每次都有", "有时候有", "没有", "我没有拿到工资单", "不确定"] },
      { id: "m2_ever_paid_overtime", label: "您有没有拿到过加班费？", type: "select", options: ["有", "没有", "有时候有", "不确定"] },
      { id: "m2_double_time_on_stub", label: "对于一天超过12小时的部分，工资单上有没有把超过12小时的每一个小时都按双倍工资（平常时薪的两倍）来算？", type: "select", options: ["每次都有", "有时候有", "没有", "我没有拿到工资单", "不确定"] },
      { id: "m2_union_or_alt_schedule", label: "这份工作有没有工会合同，或者书面的“一周做四天、每天10小时”的排班安排？", type: "select", options: ["没有", "有工会合同", "有书面的四天、每天10小时的安排", "两者都有", "可能有", "不确定"] },
    ],
  },
  {
    id: "m2_retaliation",
    title: "在您提出工资或休息时间的问题之后",
    questions: [
      { id: "m2_spoke_up", label: "您是否做过以下任何一件事？", type: "multiselect", options: ["我要求补发少发的工资", "我询问过加班费的问题", "我说过我的工时记录有误", "我要求过完整的用餐时间或休息时间", "我说过休息时间被漏掉、推迟、缩短或被打断", "我拒绝无薪工作", "我帮助过其他工人提出问题", "我提出了申诉，或说过我可能会提出申诉", "以上都没有", "不确定"], helpText: "请选出您做过的所有事项。" },
      { id: "m2_spoke_up_what", label: "您当时说了什么或问了什么？", type: "textarea", helpText: "请用您自己的话写，尽量接近您记得的原话。" },
      { id: "m2_spoke_up_who_heard", label: "谁听到了，或者谁收到了您的消息？", type: "text", helpText: "可以写全名、名字、职位、外号，或者清楚的描述。" },
      { id: "m2_spoke_up_when", label: "您大约是什么时候说的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，也可以写工作中发生的某件事——比如\"新经理来上班的那一周\"就是一个有效的回答。写\"不确定\"也可以。" },
      { id: "m2_spoke_up_how", label: "您是通过什么方式说的？", type: "select", options: ["当面说的", "打电话", "短信", "电子邮件", "群聊", "书面投诉", "向政府部门提出申诉", "其他", "不确定"] },
      { id: "m2_company_immediate_response", label: "您提出之后，公司马上做了什么？", type: "select", options: ["解决了问题", "说会去核查", "什么也没做", "说我搞错了", "和我争辩", "警告或威胁我", "其他情况", "不确定"] },
      { id: "m2_what_changed_after", label: "您提出之后，工作上有什么变化？", type: "select", options: ["没有任何变化", "有些方面变好了", "有些方面变差了", "有些方面变好了，有些方面变差了", "不确定"] },
      { id: "m2_what_got_worse", label: "您提出之后，有哪些方面变差了？", type: "multiselect", options: ["我被解雇或被裁员", "我的工时被削减", "我的工资被降低", "我被排到更差的日子或班次", "我被安排更累或更差的工作", "我被书面警告或受到处分", "我被停职", "我被调到更低的职位", "我被调岗", "我失去了升职、休假或其他机会", "我被更严密地盯着", "我被孤立或被恶劣对待", "我受到威胁", "有人拿我的移民身份来威胁我", "我感到被迫辞职", "发生了其他事情", "没有什么变差", "不确定"] },
      { id: "m2_first_bad_thing", label: "您提出之后，第一件不好的事情是什么？", type: "select", helpText: "以下是您刚才选择的项目。请选出最先发生的那一件。" },
      { id: "m2_first_bad_when", label: "那件事大约是什么时候发生的？", type: "text", helpText: "可以写确切日期、您的大致估计、某个月份或季节，也可以写工作中发生的某件事——比如\"新经理来上班的那一周\"就是一个有效的回答。写\"不确定\"也可以。" },
      { id: "m2_who_decided", label: "是谁做出或批准了这个决定？", type: "text", helpText: "可以写姓名、职位、外号，或者清楚的描述。" },
      { id: "m2_decider_knew", label: "那个人知道您就工资或休息时间提出过问题吗？", type: "select", options: ["知道", "不知道", "可能知道", "不确定"] },
      { id: "m2_how_you_know_they_knew", label: "您怎么知道那个人是知情的？", type: "textarea" },
      { id: "m2_company_reason", label: "公司为它的做法给出了什么理由？", type: "text", helpText: "写\"没有给出任何理由\"也是有效的回答，写\"不确定\"也可以。" },
      { id: "m2_reason_given_before", label: "在您提出问题之前，公司是否就跟您说过这个理由？", type: "select", options: ["是", "否", "不确定"] },
      { id: "m2_anyone_linked_it", label: "有没有人说过或写过，这件不好的事是因为您提出问题才发生的？", type: "select", options: ["有", "没有", "可能有", "不确定"] },
      { id: "m2_what_was_said", label: "具体说了什么或写了什么？", type: "textarea" },
      { id: "m2_retaliation_records", label: "哪些记录可能有助于证明发生过的事情？", type: "multiselect", options: ["短信", "电子邮件", "群聊", "工资记录", "工时记录", "排班表", "书面处分", "警告通知", "离职文件", "照片或视频", "其他", "目前没有", "不确定"] },
    ],
  },
]
